# **- Questions**

In [ ]:
#First Question
grades = [85, 92, 76, 92, 100, 76, 85, 92]

unique_grades = list(set(grades))
print("Unique grades:", unique_grades)

highest = max(unique_grades)
lowest = min(unique_grades)
print("Highest grade:", highest)
print("Lowest grade:", lowest)

sorted_grades = sorted(unique_grades)
print("Sorted grades (ascending):", sorted_grades)

Unique grades: [100, 92, 85, 76]
Highest grade: 100
Lowest grade: 76
Sorted grades (ascending): [76, 85, 92, 100]


In [ ]:
#Second Question
def is_armstrong(number):
    digits = str(number)
    power = len(digits)  # number of digits

    # Build expression string like "1^3 + 5^3 + 3^3"
    terms = [f"{digit}^{power}" for digit in digits]
    expression = " + ".join(terms)

    total = sum(int(digit) ** power for digit in digits)
    print(f"{number} → {expression} = {total}")
    return total == number

num = int(input("Enter a number: "))

if is_armstrong(num):
    print(f"{num} is an Armstrong number.")
else:
    print(f"{num} is NOT an Armstrong number.")

Enter a number: 153
153 → 1^3 + 5^3 + 3^3 = 153
153 is an Armstrong number.


In [ ]:
# Third Question
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

# Find common languages (intersection)
common = A & B
print("Common languages:", common)

# Find languages only in A (difference)
only_in_A = A - B
print("Languages only in A:", only_in_A)

# Find union of both sets and sort alphabetically
union_sorted = sorted(A | B)
print("Union of both sets (alphabetical):", union_sorted)

Common languages: {'Python', 'SQL'}
Languages only in A: {'Java', 'R'}
Union of both sets (alphabetical): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [ ]:
# Forth Question
import random
import statistics

numbers = [random.randint(1, 100) for _ in range(10)]
print("Random numbers:", numbers)

mean_value = statistics.mean(numbers)
print("Mean of numbers:", mean_value)

stdev_value = statistics.stdev(numbers)
print("Standard deviation of numbers:", stdev_value)

Random numbers: [51, 89, 82, 59, 70, 41, 42, 19, 39, 79]
Mean of numbers: 57.1
Standard deviation of numbers: 22.585393509965684


In [ ]:
# Fifth Question
def word_counter(text):
    words = text.split()
    total_words = len(words)
    longest_word = max(words, key=len)
    most_frequent = max(set(words), key=words.count)
    return total_words, longest_word, most_frequent

sentence = input("Enter a sentence: ")
total, longest, frequent = word_counter(sentence)

print("Total words:", total)
print("Longest word:", longest)
print("Most frequent word:", frequent)

Enter a sentence: Python is comfortable and python is powerful
Total words: 7
Longest word: comfortable
Most frequent word: is


In [ ]:
# Sixth Question
numbers = [5, 12, 7, 18, 24, 3, 16]

even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print("Even numbers:", even_numbers)

squares = list(map(lambda x: x ** 2, even_numbers))
print("Squares of even numbers:", squares)

sorted_squares = sorted(squares, reverse=True)
print("Squares sorted in descending order:", sorted_squares)

Even numbers: [12, 18, 24, 16]
Squares of even numbers: [144, 324, 576, 256]
Squares sorted in descending order: [576, 324, 256, 144]


In [ ]:
# Seventh Question
words = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sorted_words = sorted(words, key=lambda x: len(x))
print("Words sorted by length:", sorted_words)

Words sorted by length: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [ ]:
# Eighth Question
def sum_digits(text):
    digits = [int(char) for char in text if char.isdigit()]

    total = sum(digits)
    return total

user_input = input("Enter a string: ")
result = sum_digits(user_input)

print("Sum of all digits in the string:", result)

Enter a string: asf52yu8p4
Sum of all digits in the string: 19


In [ ]:
# Nineth Question
import numpy as np

arr = np.random.randint(0, 51, size=10)
print("Random array:", arr)

mean_value = np.mean(arr)
print("Mean of the array:", mean_value)

stdev_value = np.std(arr)
print("Standard deviation of the array:", stdev_value)

max_value = np.max(arr)
print("Maximum value in the array:", max_value)

Random array: [39 27 12 37 10 10 22 39 42 36]
Mean of the array: 27.4
Standard deviation of the array: 12.330450113438683
Maximum value in the array: 42


In [ ]:
# Tenth Question
import numpy as np

matrix = np.random.rand(5, 5)
print("Random 5x5 matrix:\n", matrix)

column_means = np.mean(matrix, axis=0)
print("Column means:", column_means)

binary_matrix = (matrix > 0.5).astype(int)
print("Binary matrix:\n", binary_matrix)

Random 5x5 matrix:
 [[0.75101094 0.37088137 0.04261671 0.00868356 0.54242395]
 [0.95389035 0.99248189 0.91251373 0.39455994 0.5918336 ]
 [0.99710486 0.85048893 0.74753308 0.39176101 0.90672322]
 [0.85412426 0.92711133 0.87993102 0.47440227 0.99551082]
 [0.25978568 0.7322787  0.88646411 0.25952703 0.51278059]]
Column means: [0.76318322 0.77464844 0.69381173 0.30578676 0.70985444]
Binary matrix:
 [[1 0 0 0 1]
 [1 1 1 0 1]
 [1 1 1 0 1]
 [1 1 1 0 1]
 [0 1 1 0 1]]
